springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
spring.mvc.servlet.context-path=/api

logging.level.root=INFO
logging.level.com.miempresa=DEBUG
logging.level.org.springframework.web=ERROR

spring.h2.console.path=/h2-console

spring.sql.init.platform=h2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.h2.console.enabled=true

server.address=0.0.0.0
spring.profiles.active=prod
